In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,200,(3,3))

In [4]:
arr

array([[113,   9, 105],
       [106, 190, 118],
       [116,  17,  99]])

In [ ]:
arr.reshape(6,2)

In [5]:
arr.T

array([[113, 106, 116],
       [  9, 190,  17],
       [105, 118,  99]])

In [7]:
arr.flatten()#To Convert any dimensional into one dimension

array([113,   9, 105, 106, 190, 118, 116,  17,  99])

In [8]:
arr1=np.random.randint(1,123,(3,5))

In [9]:
arr1.flatten()

array([ 64,  38, 121, 115,  88, 101,  46,  79,  66,   8, 110, 103,  97,
        14,  29])

In [10]:
arr1.ndim

2

In [ ]:
arr.expand

In [16]:
arr=np.array([[1],[2],[3]])

In [17]:
arr

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(arr)

array([1, 2, 3])

In [20]:
arr.flatten()==np.squeeze(arr)

array([ True,  True,  True])

In [ ]:
#Binary Operation

In [21]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [22]:
arr1

array([[6, 6, 6, 5],
       [2, 7, 3, 5],
       [8, 7, 5, 2]])

In [24]:
arr2

array([[9, 5, 2, 1],
       [2, 5, 9, 2],
       [5, 3, 4, 7]])

In [25]:
arr1 & arr2

array([[0, 4, 2, 1],
       [2, 5, 1, 0],
       [0, 3, 4, 2]])

In [26]:
arr1 | arr2

array([[15,  7,  6,  5],
       [ 2,  7, 11,  7],
       [13,  7,  5,  7]])

In [27]:
~arr1

array([[-7, -7, -7, -6],
       [-3, -8, -4, -6],
       [-9, -8, -6, -3]])

In [ ]:
#String Functions


In [28]:
arr=np.array(['sudh','Kumar'])

In [29]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [ ]:
# Sort,Search & counting functions
