In [3]:
import numpy as np

In [5]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.linspace(2,4,100)

array([2.        , 2.02020202, 2.04040404, 2.06060606, 2.08080808,
       2.1010101 , 2.12121212, 2.14141414, 2.16161616, 2.18181818,
       2.2020202 , 2.22222222, 2.24242424, 2.26262626, 2.28282828,
       2.3030303 , 2.32323232, 2.34343434, 2.36363636, 2.38383838,
       2.4040404 , 2.42424242, 2.44444444, 2.46464646, 2.48484848,
       2.50505051, 2.52525253, 2.54545455, 2.56565657, 2.58585859,
       2.60606061, 2.62626263, 2.64646465, 2.66666667, 2.68686869,
       2.70707071, 2.72727273, 2.74747475, 2.76767677, 2.78787879,
       2.80808081, 2.82828283, 2.84848485, 2.86868687, 2.88888889,
       2.90909091, 2.92929293, 2.94949495, 2.96969697, 2.98989899,
       3.01010101, 3.03030303, 3.05050505, 3.07070707, 3.09090909,
       3.11111111, 3.13131313, 3.15151515, 3.17171717, 3.19191919,
       3.21212121, 3.23232323, 3.25252525, 3.27272727, 3.29292929,
       3.31313131, 3.33333333, 3.35353535, 3.37373737, 3.39393939,
       3.41414141, 3.43434343, 3.45454545, 3.47474747, 3.49494

In [12]:
np.logspace(2,5,10,base=10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [16]:
np.random.rand(3,4)

array([[0.38417703, 0.25542949, 0.72995404, 0.93327157],
       [0.97744098, 0.94677318, 0.51329811, 0.50073616],
       [0.89817747, 0.37399842, 0.03397965, 0.74108652]])

In [17]:
np.random.randn(3,4)

array([[ 0.95766695,  0.95010276,  0.42925766, -1.44468039],
       [-1.00420383, -0.95053671, -0.73493518,  0.16851088],
       [-1.23797588, -1.25311636,  0.83467747,  0.5638199 ]])

In [31]:
cd=np.random.randn(3,4)

In [32]:
ab=np.random.randint(1,1000,(35,45))

In [33]:
import pandas as pd

In [34]:
# pd.DataFrame(ab).to_csv('random.csv')

In [37]:
cd.reshape(4,-1)

array([[-0.09895413,  1.56838812,  2.78418754],
       [-1.77607655, -0.45713596, -1.40912848],
       [-0.85237277, -1.1872031 ,  0.8083733 ],
       [-0.67557225,  0.52868644,  0.34994848]])

In [43]:
arr = np.random.randint(1,100,(5,4))
arr

array([[35,  3, 32, 93],
       [70, 32,  6, 78],
       [17, 84, 34, 88],
       [76, 32, 13, 23],
       [27, 15, 11, 21]])

In [44]:
arr>50

array([[False, False, False,  True],
       [ True, False, False,  True],
       [False,  True, False,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [45]:
arr[arr>50]

array([93, 70, 78, 84, 88, 76])

In [47]:
arr = np.random.randint(1,100,(5,4))
arr

array([[21, 29, 84,  8],
       [32, 33,  1, 41],
       [17, 25, 95, 18],
       [21, 49, 61,  3],
       [55, 25, 71, 79]])

In [51]:
arr[2:5,[1,2,3]]

array([[25, 95, 18],
       [49, 61,  3],
       [25, 71, 79]])

In [52]:
arr = np.random.randint(1,100,(5,4))
arr

array([[ 4, 69, 10,  7],
       [72, 17, 23, 46],
       [48, 30, 70, 92],
       [ 2, 47, 52, 12],
       [54, 41, 15, 40]])

In [54]:
arr[2:4,[1,2]]

array([[30, 70],
       [47, 52]])

In [55]:
arr1=np.random.randint(1,6,(3,4))
arr2=np.random.randint(2,5,(3,4))

In [58]:
arr1


array([[4, 3, 4, 4],
       [5, 4, 3, 4],
       [3, 2, 2, 2]])

In [57]:
arr2

array([[2, 3, 2, 2],
       [2, 3, 4, 4],
       [4, 3, 4, 3]])

In [59]:
arr1+arr2

array([[6, 6, 6, 6],
       [7, 7, 7, 8],
       [7, 5, 6, 5]])

In [60]:
arr1*arr2

array([[ 8,  9,  8,  8],
       [10, 12, 12, 16],
       [12,  6,  8,  6]])

In [67]:
arr11=np.random.randint(1,6,(4,4))
arr22=np.random.randint(2,5,(4,4))

In [70]:
ans=arr11@arr22

In [71]:
np.sqrt(ans)

array([[6.08276253, 6.164414  , 5.74456265, 5.91607978],
       [6.63324958, 6.63324958, 6.164414  , 6.244998  ],
       [5.        , 4.89897949, 5.38516481, 4.89897949],
       [6.4807407 , 6.4807407 , 6.70820393, 6.08276253]])

In [72]:
np.exp(ans)

array([[1.17191424e+16, 3.18559318e+16, 2.14643580e+14, 1.58601345e+15],
       [1.28516001e+19, 1.28516001e+19, 3.18559318e+16, 8.65934004e+16],
       [7.20048993e+10, 2.64891221e+10, 3.93133430e+12, 2.64891221e+10],
       [1.73927494e+18, 1.73927494e+18, 3.49342711e+19, 1.17191424e+16]])

In [74]:
np.log2(ans)

array([[5.20945337, 5.24792751, 5.04439412, 5.12928302],
       [5.45943162, 5.45943162, 5.24792751, 5.28540222],
       [4.64385619, 4.5849625 , 4.857981  , 4.5849625 ],
       [5.39231742, 5.39231742, 5.4918531 , 5.20945337]])