In [2]:
import numpy as np

In [11]:
np.fromfunction(lambda x,y:x==y,(5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [12]:
np.fromfunction(lambda x,y:x**y,(5,5))

array([[  1.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.,  16.],
       [  1.,   3.,   9.,  27.,  81.],
       [  1.,   4.,  16.,  64., 256.]])

In [13]:
l=[2,3,4,5]


In [14]:
arr=np.array(l)

In [15]:
arr

array([2, 3, 4, 5])

In [16]:
arr2=np.array([[1,2,3],[4,5,6],[5,6,7]])

In [18]:
arr2.ndim

2

In [19]:
arr2.size

9

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [22]:
arr2.shape

(3, 3)

In [24]:
np.arange(1.2,102.2)

array([  1.2,   2.2,   3.2,   4.2,   5.2,   6.2,   7.2,   8.2,   9.2,
        10.2,  11.2,  12.2,  13.2,  14.2,  15.2,  16.2,  17.2,  18.2,
        19.2,  20.2,  21.2,  22.2,  23.2,  24.2,  25.2,  26.2,  27.2,
        28.2,  29.2,  30.2,  31.2,  32.2,  33.2,  34.2,  35.2,  36.2,
        37.2,  38.2,  39.2,  40.2,  41.2,  42.2,  43.2,  44.2,  45.2,
        46.2,  47.2,  48.2,  49.2,  50.2,  51.2,  52.2,  53.2,  54.2,
        55.2,  56.2,  57.2,  58.2,  59.2,  60.2,  61.2,  62.2,  63.2,
        64.2,  65.2,  66.2,  67.2,  68.2,  69.2,  70.2,  71.2,  72.2,
        73.2,  74.2,  75.2,  76.2,  77.2,  78.2,  79.2,  80.2,  81.2,
        82.2,  83.2,  84.2,  85.2,  86.2,  87.2,  88.2,  89.2,  90.2,
        91.2,  92.2,  93.2,  94.2,  95.2,  96.2,  97.2,  98.2,  99.2,
       100.2, 101.2])

In [31]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])